# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProjectVec <- function(xi, xj, dij) {
    .Call('cmdsr_ProjectVec', PACKAGE = 'cmdsr', xi, xj, dij)
}

ProjectC <- function(Dtau, Xtau, i) {
    .Call('cmdsr_ProjectC', PACKAGE = 'cmdsr', Dtau, Xtau, i)
}

MajoriseC <- function(Dlist, Xlist, i, params) {
    .Call('cmdsr_MajoriseC', PACKAGE = 'cmdsr', Dlist, Xlist, i, params)
}

MinimiseC <- function(XauxList, i, params) {
    .Call('cmdsr_MinimiseC', PACKAGE = 'cmdsr', XauxList, i, params)
}

CenterConfiguration <- function(XList, params) {
    invisible(.Call('cmdsr_CenterConfiguration', PACKAGE = 'cmdsr', XList, params))
}

MinimiseWeighted <- function(XauxList, WList, i, params) {
    .Call('cmdsr_MinimiseWeighted', PACKAGE = 'cmdsr', XauxList, WList, i, params)
}

OptimiseCurve <- function(Dlist, Xlist, i, params) {
    .Call('cmdsr_OptimiseCurve', PACKAGE = 'cmdsr', Dlist, Xlist, i, params)
}

OptimiseAllCurves <- function(Dlist, Xlist, params) {
    invisible(.Call('cmdsr_OptimiseAllCurves', PACKAGE = 'cmdsr', Dlist, Xlist, params))
}

OuterLoop <- function(Dlist, Xlist, params, maxIter) {
    .Call('cmdsr_OuterLoop', PACKAGE = 'cmdsr', Dlist, Xlist, params, maxIter)
}

